chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('message_request/<str:requestUser>/<str:fromPage>/', message_request_update, name='message_request_update'),
    # path('message_request_list/', RequestView.as_view(), name='message_request_list'),
    path('create/', create_room, name='create_room'),
    path('create_group/', CreateGroupView.as_view(), name='creategroup'),
    path('groups/', index_group, name='groupindex'),
    path('group/<int:room_name>/', group, name="group"),
    path('room/<int:room_name>/', room, name='room'),
    path('create/<slug:slug>/', landlord_chat, name='landlordchat'),
    path('landlord/student/create/<str:studuser>/', landlord_student_chat, name="landlordStudentChat"),
]

property/urls.py
from django.urls import path
from .views import *

app_name = 'property'

urlpatterns = [    
    path("property/", PropertyListView.as_view(), name="propertyList"),
    path("property/create/", PropertyCreateView.as_view(), name="propertyCreate"),
    path("property/update/<slug:slug>/", PropertyUpdateView.as_view(), name="propertyUpdate"),
    path("property/delete/<slug:slug>/", PropertyDeleteView.as_view(), name="propertyDelete"),
    path("property/<slug:slug>/", PropertyDetailView.as_view(), name="propertyDetail"),
    path("property/reaction/<slug:slug>/", LikesDisLikesView, name="propertyReaction"),
    path("property/question/<slug:slug>/", PostQuestionView, name="propertyQuestion"),
    path("property/answer/<int:pk>/", PostAnswerView, name="propertyAnswer"),
    path("property/question/delete/<int:pk>/", PostQuestionDeleteView, name="questionDelete"),
    path("myproperty/", LandlordManageProperty.as_view(), name="propertyManage"),
    path("vaccant/<slug:slug>/", VaccantChangeView, name="vaccant"),
    path("property/<slug:slug>/tag/friend/", TagFriendsView, name="tagFriend"),
]

realestatex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/defender/', include('defender.urls')),
    path('', include("users.urls", namespace='userApp')),
    path('',include("property.urls", namespace='propertyApp')),
    path('', include("students.urls", namespace='studentsApp')),
    path('', include("services.urls", namespace='servicesApp')),
    path('', include("checkout.urls", namespace='checkoutApp')),
    path('', include("notifications.urls", namespace='notificationApp')),
    path('', include("discussion.urls", namespace='discussionApp')),
    path('chat/', include("chat.urls", namespace='chatApp')),
    path('', include("resources.urls", namespace='resourcesApp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from .views import *


app_name = 'students'

urlpatterns = [
    path('favorites/', FavoriteListView.as_view(), name="favorites"),
    # path('favorites/add/<slug:slug>/', AddFavorite, name="addFavorites"),
    # path('favorites/remove/<slug:slug>/', RemoveFavorite, name="removeFavorites"),

    path('roommates/', RoommatesListView.as_view(), name="roommates"),
    path('roommates/mypost/', RoommatesMyPostListView.as_view(), name="roommatesMypost"),
    
    #enable if preferences
    # path('roommates/<slug:preference>/', RoommatesListView.as_view(), name="roommatesPreference"),
    # path('roommates/<slug:preference>/post/create/', RoommatesPostCreateView.as_view(), name="postCreate"),

    path('roommates/post/create/', RoommatesPostCreateView.as_view(), name="postCreate"),
    path('roommates/post/<int:pk>/update/', RoommatesPostUpdateDeleteView.as_view(), name="postUpdate"),
    path('roommates/post/<int:pk>/', RoommatesPostDetailView.as_view(), name="postDetail"),
    path('roommates/post/<int:pk>/delete/', RoommatesPostUpdateDeleteView.as_view(), name="postDelete"),

    path('roommates/post/<int:pk>/heart/', AddRemoveHeart, name="addRemoveHeart"),

    path('roommates/<int:pk>/comment/create/', PostCommentCreateView.as_view(), name="commentCreate"),
    path('roommates/comment/<int:pk>/', PostCommentUpdateDeleteView.as_view(), name="commentUpdateDelete"),

    path('roommates/comment/<int:pk>/reply/create/', CommentReplyCreateView.as_view(), name="replyCreate"),
    path('roommates/reply/<int:pk>/', CommentReplyUpdateDeleteView.as_view(), name="replyUpdateDelete"),
]

property/models.py
from django.db import models
from django.contrib.gis.db import models as geoModel
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator, RegexValidator
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_delete, post_save
from django.contrib.gis.geos import fromstr
from django.contrib.gis.db.models.functions import Distance
from django.utils import timezone
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

import datetime, os

from users.models import UserLandLord, UserStudent
from .utils import unique_slug_generator, unique_file_path_generator, random_string_generator
from .locationApi import get_lat_long_from_address, get_near_by_text_places, get_near_by_types, logging
from .taskSchedulers import scheduler


# Create your models here.
class StateList(models.Model):
    stateFullName = models.CharField(max_length=150,
                                     help_text="Full name of State. Eg Newyork",
                                     verbose_name="State Name"
                                     )
    stateShortName = models.CharField(max_length=10,
                                      help_text="Short name of a state. Eg Newyork - NY",
                                      verbose_name="Short Form"
                                      )

    def __str__(self):
        return self.stateFullName


class CityList(models.Model):
    state = models.ForeignKey(StateList, on_delete=models.CASCADE)
    cityName = models.CharField(max_length=150, help_text="City Name. Eg Stony Brook")

    def __str__(self):
        return '{}, {}'.format(self.cityName, self.state.stateShortName)


class Amenities(models.Model):
    amenityType = models.CharField(max_length=100, help_text="Type of Amenity. eg Pool, GYM etc",
                                   verbose_name="Amenity Type")

    class Meta:
        verbose_name_plural = "Amenities"

    def __str__(self):
        return self.amenityType

    def clean(self):
        self.amenityType = self.amenityType.capitalize()
        if Amenities.objects.filter(amenityType=self.amenityType):
            raise ValidationError({'amenityType': ValidationError(('Amenity already exists'), code='error')})


class Property(geoModel.Model):
    landlord = models.ForeignKey(UserLandLord, on_delete=models.CASCADE)
    urlSlug = models.SlugField(unique=True, max_length=200, editable=False, verbose_name='URL')
    title = models.CharField(max_length=150, help_text="Title for your property")
    city = models.ForeignKey(CityList, on_delete=models.CASCADE, help_text="Select property located city")
    zipcode = models.CharField(max_length=5, verbose_name="Zip or Postal Code", validators=[
        RegexValidator(regex=r'^\d{5}$', message='Only numbers allowed.'),
        MinLengthValidator(5, '5 digit code'),
    ], help_text="Eg 503 - 00503")
    address = models.CharField(max_length=250, help_text="Address of your property")
    location = geoModel.PointField(null=True, blank=True)
    locationType = models.CharField(null=True, blank=True, max_length=200)
    averageDistance = models.FloatField(default=0,
                                        help_text='Average distance between the nearby amenities (in miles).')
    placeId = models.CharField(null=True, blank=True, max_length=300)
    sqft = models.FloatField(
        null=True, blank=True, verbose_name="Square Feet",
        help_text="Total Square feet of property",
        validators=[MinValueValidator(1, "Square Feet should be atleast 1.")]
    )
    occupants = models.IntegerField(help_text="Number of people can stay", validators=[
        MinValueValidator(1, "Minimum 1"),
        MaxValueValidator(20, "Maximum 20")
    ])
    rooms = models.IntegerField(help_text="Available Rooms", verbose_name="Bedrooms", validators=[
        MinValueValidator(1, "Minimum 1"),
        MaxValueValidator(20, "Maximum 20")
    ])
    bathrooms = models.IntegerField(help_text="Number of Bathrooms", validators=[
        MinValueValidator(1, "Minimum 1"),
        MaxValueValidator(20, "Maximum 20")
    ])
    securityDeposit = models.BooleanField(default=False,
                                          help_text="Select if security deposit needed",
                                          verbose_name="Security Deposit"
                                          )
    amount = models.IntegerField(null=True, blank=True, help_text="Security Deposit Amount in $",
                                 validators=[MinValueValidator(0, 'Minimum Amount cannot be lower than 0')]
                                 )
    rent = models.IntegerField(verbose_name="Total Rent", help_text="Amount in $",
                               validators=[MinValueValidator(0, 'Minimum Price cannot be lower than 0')]
                               )
    description = models.TextField(help_text="Describe about your property", max_length=500)
    # utilities = models.BooleanField(default=False, help_text="Select if you have Utilities")
    garage = models.BooleanField(default=False, help_text="Select if you have Garage")
    parkingSpace = models.IntegerField(verbose_name="Parking Space",
                                       help_text="Available Parking Space. Eg 1 or 2",
                                       validators=[
                                           MinValueValidator(0, 'Minimum 0'),
                                           MaxValueValidator(20, 'Maximum 20')
                                       ],
                                       default=0
                                       )
    amenities = models.ManyToManyField(Amenities, help_text="Select 1 or more Amenities.")
    fromDate = models.DateField(verbose_name="From Date",
                                help_text="From which date property available for rent"
                                )
    toDate = models.DateField(verbose_name="To Date",
                              help_text="Till which the property will be available."
                              )
    likes = models.ManyToManyField(UserStudent, related_name="propLikes", blank=True)
    dislikes = models.ManyToManyField(UserStudent, related_name="propDislikes", blank=True)
    isleased = models.BooleanField(default=False)
    leaseStart = models.DateField(blank=True, null=True)
    leaseEnd = models.DateField(blank=True, null=True)
    updatedDate = models.DateTimeField(auto_now=True, verbose_name="Last Updated Date")
    createdDate = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")

    class Meta:
        verbose_name_plural = "Properties"

    @property
    def totalLikes(self):
        return self.likes.count

    @property
    def totalDislikes(self):
        return self.dislikes.count

    def clean(self):
        errorMess = {}
        hasError = False
        if self.securityDeposit and self.amount == None:
            errorMess['amount'] = ValidationError(('Amount Field is required'), code='required')
            hasError = True

        if not self.securityDeposit:
            self.amount = None

        if self.fromDate is not None:
            if self.fromDate < datetime.date.today():
                alexists = Property.objects.filter(pk=self.pk).exists()
                if alexists:
                    check = Property.objects.get(pk=self.pk)
                    if check.fromDate != self.fromDate:
                        hasError = True
                        errorMess['fromDate'] = ValidationError(('From Date cannot be older than today.'), code='error')
                else:
                    hasError = True
                    errorMess['fromDate'] = ValidationError(('From Date cannot be older than today.'), code='error')

        if self.toDate is not None:
            if self.toDate <= self.fromDate:
                hasError = True
                errorMess['toDate'] = ValidationError(('To Date cannot be less than or equal to From Date.'),
                                                      code='error')

        if self.address:
            try:
                fullAddress = '{}, {} {}'.format(self.address, self.city, self.zipcode)
                placeId, locationType, location, status = get_lat_long_from_address(fullAddress)
                # print(placeId, locationType, location, status)
                if status:
                    if placeId:
                        self.placeId = placeId
                    if locationType:
                        self.locationType = locationType
                    if location:
                        longitude = location.get('lng', 0)
                        latitude = location.get('lat', 0)
                        self.location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                else:
                    hasError = True
                    errorMess['address'] = ValidationError(
                        ('We are unable to locate the exact location. Please enter the address correctly.'),
                        code='error')
            except Exception as e:
                print(e)

        if hasError:
            raise ValidationError(errorMess)

    def __str__(self):
        return "{} {}".format(self.pk, self.title)


class PropertyImage(models.Model):
    propertyKey = models.ForeignKey(Property, on_delete=models.CASCADE)
    # imageDescription = models.CharField(max_length=50, verbose_name="Video Description")
    # imagePath = models.ImageField(upload_to=unique_file_path_generator, verbose_name="Image")
    imagePath = ProcessedImageField(upload_to=unique_file_path_generator, verbose_name="Image",
                                    processors=[ResizeToFill(2500, 2500)],
                                    options={'quality': 90})

    @property
    def mediaType(self):
        return 'propimage'

    def __str__(self):
        return "{}".format(self.pk)

students/templates/students/favorites.html
{% include "layout/google-analytics.html" %}
{% include "layout/header.html" %}

{% load static %}

		<style>
			#layoutDefault_footer { display:none; }
			.pxp-header.fixed-top.pxp-animate { background-color:rgba(4, 113, 166, 1) !important; }
			.pxp-results-card-1-save:hover { background-color:maroon; color:#fff; }
		</style>

		
            <div class="pxp-content-side pxp-content-leftt pxp-half">
			<div style="position:relative; margin-top:100px;" id="resmsg"></div>
				
                <div class="pxp-content-side-wrapper">                   
					<br><h2>My Favorites</h2>
                    <div class="row">
                        {% load humanize %}
                        {% comment %} {% for object in object_list %}
                            {% for property in object.properties.all %}
                                <div class="col-xs-12 col-sm-6 col-md-3 col-xxxl-3" id="remove{{property.pk}}">
                                    <a href="{% url 'property:propertyDetail' property.urlSlug %}" class="pxp-results-card-1 rounded-lg" data-prop="{{property.pk}}" style="box-shadow:3px 3px 5px grey;">
                                        <div id="card-carousel-{{property.pk}}" class="carousel slide" data-ride="carousel" data-interval="false">
                                            <div class="carousel-inner">
                                                {% for image in property.propertyimage_set.all %}
													{% if forloop.first %}
                                                       <div class="carousel-item active" style="background-image: url({{image.imagePath.url}})"></div>
													{% else %}
														<div class="carousel-item" style="background-image: url({{image.imagePath.url}});"></div>
													{% endif %}
												{% endfor %}
                                            </div>
                                            <span class="carousel-control-prev" data-href="#card-carousel-{{property.pk}}" data-slide="prev">
                                                <span class="fa fa-angle-left" aria-hidden="true"></span>
                                            </span>
                                            <span class="carousel-control-next" data-href="#card-carousel-{{property.pk}}" data-slide="next">
                                                <span class="fa fa-angle-right" aria-hidden="true"></span>
                                            </span>
                                        </div>
                                        <div class="pxp-results-card-1-gradient"></div>
                                        <div class="pxp-results-card-1-details">
                                            <div class="pxp-results-card-1-details-title">{{property.title|title|truncatechars:25}}</div>
                                            <div class="pxp-results-card-1-details-price">${{property.rentPerPerson|intcomma}}</div>
                                        </div>
                                        <div class="pxp-results-card-1-features">
                                            <span>{{property.rooms}} Room <span>|</span> {{property.bathrooms}} BA <span>|</span> {{property.sqft|intcomma}} SF</span>
                                        </div>
                                        
                                        <div class="pxp-results-card-1-save removebtn" key="{{csrf_token}}" removeurl="{% url 'students:removeFavorites' property.urlSlug %}" data-toggle="tooltip" title="Remove from favorites" onclick="return removefromfav('remove{{property.pk}}', this)"><span class="fa fa-times"></span></div>
                                    </a>
                                </div>
                            {% endfor %}
                        {% endfor %} {% endcomment %}
			{% if object_list %}
                        {% for object in object_list %}
                            <div class="col-xs-12 col-sm-6 col-md-3 col-xxxl-3" id="remove{{object.property.pk}}">
                                <a href="{% url 'property:propertyDetail' object.property.urlSlug %}" class="pxp-results-card-1 rounded-lg" data-prop="{{object.property.pk}}" style="box-shadow:3px 3px 5px grey;">
                                    <div id="card-carousel-{{object.property.pk}}" class="carousel slide" data-ride="carousel" data-interval="false">
                                        <div class="carousel-inner">
                                            {% for image in object.property.propertyimage_set.all %}
                                                {% if forloop.first %}
                                                    <div class="carousel-item active" style="background-image: url({{image.imagePath.url}})"></div>
                                                {% else %}
                                                    <div class="carousel-item" style="background-image: url({{image.imagePath.url}});"></div>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        <span class="carousel-control-prev" data-href="#card-carousel-{{object.property.pk}}" data-slide="prev">
                                            <span class="fa fa-angle-left" aria-hidden="true"></span>
                                        </span>
                                        <span class="carousel-control-next" data-href="#card-carousel-{{object.property.pk}}" data-slide="next">
                                            <span class="fa fa-angle-right" aria-hidden="true"></span>
                                        </span>
                                    </div>
                                    <div class="pxp-results-card-1-gradient"></div>
                                    <div class="pxp-results-card-1-details">
                                        <div class="pxp-results-card-1-details-title">{{object.property.title|title|truncatechars:25}}</div>
                                        <div class="pxp-results-card-1-details-price">${{object.property.rentPerPerson|intcomma}}</div>
                                    </div>
                                    <div class="pxp-results-card-1-features">
                                        <span>{{object.property.rooms}} Room <span>|</span> {{object.property.bathrooms}} BA <span>|</span> {{object.property.sqft|intcomma}} SF</span>
                                    </div>
                                    
                                    <div class="pxp-results-card-1-save removebtn" key="{{csrf_token}}" removeurl="{% url 'property:propertyReaction' object.property.urlSlug %}" data-toggle="tooltip" title="Remove from favorites" onclick="return removefromfav('remove{{object.property.pk}}', this)"><span class="fa fa-times"></span></div>
                                </a>
                            </div>
                        {% endfor %}
			{% else %}
				<center>
					<div class="container-fluid" style="min-height:350px; min-width:100%;">
							<div class="alert alert-warning" style="width:100%; border-radius:10px;">
								<h5 style="color:maroon;"><i> No favorite added yet! </i></h5>
							</div>
					</div>
				</center>
			{% endif %}
                    </div>
                </div>
		
		<script src="js/jquery-3.4.1.min.js"></script>
		
		<script>
			$(document).ready(function(){
			  $('[data-toggle="tooltip"]').tooltip({html:true});
			});			
		</script>
		
		<script>
		
			function removefromfav(id, dis)
			{
				if(confirm("Are you sure to remove this property from favorites?") == true) {
					$("#"+id).hide(500);
                    var url = dis.getAttribute('removeurl');
                    var csrfmiddlewaretoken = dis.getAttribute('key');
                    $.ajax({
                    url: url,
                    type: 'POST',
                    data: {"like":1, "csrfmiddlewaretoken": csrfmiddlewaretoken,},
                    success: function(res){
                        console.log(res);
                    },
                    error: function(){
                        console.log('Error!');
                    }
                    });
					setTimeout(function() {
						$("#resmsg").html(" &nbsp; &nbsp; <span class='alert alert-danger alert-xs pull-right' id='lastmsg' style='color:maroon;'>Favorite deleted!</span> &nbsp; <br>");
					}, 700);
					setTimeout(function() {
						$("#lastmsg").fadeOut(2000);
					}, 2000);
					return false;
				} else {
					return false;
				}				
			}
			
		</script>


{% include "layout/footer.html" %}