chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('message_request/<str:requestUser>/<str:fromPage>/', message_request_update, name='message_request_update'),
    # path('message_request_list/', RequestView.as_view(), name='message_request_list'),
    path('create/', create_room, name='create_room'),
    path('create_group/', CreateGroupView.as_view(), name='creategroup'),
    path('groups/', index_group, name='groupindex'),
    path('group/<int:room_name>/', group, name="group"),
    path('room/<int:room_name>/', room, name='room'),
    path('create/<slug:slug>/', landlord_chat, name='landlordchat'),
    path('landlord/student/create/<str:studuser>/', landlord_student_chat, name="landlordStudentChat"),
]

checkout/urls.py
from django.urls import path

from .views import *

app_name = "checkout"

urlpatterns = [
    path('property/<slug:slug>/request-to-rent/', RequestToRentPropertyCreateView, name="requestRent"),
    path('property/<slug:slug>/request-to-tour/', RequestToTourPropertyCreateView, name="requestTour"),
    path('services/<int:pk>/request-to-rent/', RequestToRentServiceCreateView, name="requestService"),
    path('myrequests/', myrequest, name="myrequest"),
    path('request/rent/<int:pk>/', RequestToRentPropertyDetailView.as_view(), name="rentRequestDetail"),
    path('request/tour/<int:pk>/', RequestToTourPropertyDetailView.as_view(), name="tourRequestDetail"),
]

property/urls.py
from django.urls import path
from .views import *

app_name = 'property'

urlpatterns = [    
    path("property/", PropertyListView.as_view(), name="propertyList"),
    path("property/create/", PropertyCreateView.as_view(), name="propertyCreate"),
    path("property/update/<slug:slug>/", PropertyUpdateView.as_view(), name="propertyUpdate"),
    path("property/delete/<slug:slug>/", PropertyDeleteView.as_view(), name="propertyDelete"),
    path("property/<slug:slug>/", PropertyDetailView.as_view(), name="propertyDetail"),
    path("property/reaction/<slug:slug>/", LikesDisLikesView, name="propertyReaction"),
    path("property/question/<slug:slug>/", PostQuestionView, name="propertyQuestion"),
    path("property/answer/<int:pk>/", PostAnswerView, name="propertyAnswer"),
    path("property/question/delete/<int:pk>/", PostQuestionDeleteView, name="questionDelete"),
    path("myproperty/", LandlordManageProperty.as_view(), name="propertyManage"),
    path("vaccant/<slug:slug>/", VaccantChangeView, name="vaccant"),
    path("property/<slug:slug>/tag/friend/", TagFriendsView, name="tagFriend"),
]

realestatex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/defender/', include('defender.urls')),
    path('', include("users.urls", namespace='userApp')),
    path('',include("property.urls", namespace='propertyApp')),
    path('', include("students.urls", namespace='studentsApp')),
    path('', include("services.urls", namespace='servicesApp')),
    path('', include("checkout.urls", namespace='checkoutApp')),
    path('', include("notifications.urls", namespace='notificationApp')),
    path('', include("discussion.urls", namespace='discussionApp')),
    path('chat/', include("chat.urls", namespace='chatApp')),
    path('', include("resources.urls", namespace='resourcesApp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

checkout/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox, ReCaptchaV3

from .models import RequestToRentProperty, RequestToTourProperty, RequestToRentService


class RequestToRentPropertyForm(forms.ModelForm):
    rentcaptcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

    class Meta:
        model = RequestToRentProperty
        fields = ['occupants', 'moveIn', 'moveOut']

        widgets = {
            'occupants': forms.NumberInput(attrs={
                'class': 'form-control forminputrequests',
            }),
            'moveIn': forms.DateInput(attrs={
                'class': 'form-control forminputrequests',
                'type': 'date'
            }),
            'moveOut': forms.DateInput(attrs={
                'class': 'form-control forminputrequests',
                'type': 'date'
            })
        }


class RequestToTourPropertyForm(forms.ModelForm):

    tourcaptcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

    class Meta:
        model = RequestToTourProperty
        fields = ['preference1Date', 'preference1Time', 'preference2Date', 'preference2Time', 
                    'preference3Date', 'preference3Time']

        widgets = {
            'preference1Date': forms.DateInput(attrs={
                'class': 'form-control forminputrequests',
                'type': 'date'
            }),
            'preference1Time': forms.TimeInput(attrs={
                'class': 'form-control forminputrequests',
                'type': 'time'
            }),
            'preference2Date': forms.DateInput(attrs={
                'class': 'form-control forminputrequests',
                'type': 'date'
            }),
            'preference2Time': forms.TimeInput(attrs={
                'class': 'form-control forminputrequests',
                'type': 'time'
            }),
            'preference3Date': forms.DateInput(attrs={
                'class': 'form-control forminputrequests',
                'type': 'date'
            }),
            'preference3Time': forms.TimeInput(attrs={
                'class': 'form-control forminputrequests',
                'type': 'time'
            }),
        }


class RequestToRentServiceForm(forms.ModelForm):

    servicecaptcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

    class Meta:
        model = RequestToRentService
        exclude = ('serviceObj', 'studentObj', 'status')

        widgets = {
            'fromDate': forms.DateInput(attrs={
                'class': 'form-control',
                'style': 'width:100%; border-radius:50px;',
                'type': 'date'
            }),
            'toDate': forms.DateInput(attrs={
                'class': 'form-control',
                'style': 'width:100%; border-radius:50px;',
                'type': 'date'
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter First name',
                'style' : 'width:100%; border-radius:50px;'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Last name',
                'style' : 'width:100%; border-radius:50px;'
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'tel',
                'placeholder': 'Your Phone Number',
                'style': 'border-radius:50px;',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Your Email',
                'style' : 'border-radius:50px;',
            }),
            'deliveryAddress': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Delivery Address',
                'style' : 'border-radius:30px;',
                'rows': '2',
            })
        }

checkout/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DetailView
from django.contrib import messages
from django.contrib.auth import get_user_model

from .models import RequestToRentProperty, RequestToRentService, RequestToTourProperty
from .forms import RequestToRentPropertyForm, RequestToRentServiceForm, RequestToTourPropertyForm
from property.utils import studentAccessTest, landlordAccessTest
from property.models import Property
from services.models import Service
from users.models import UserStudent
from notifications.models import Notification
# Create your views here.

@login_required
@user_passes_test(studentAccessTest)
def RequestToRentPropertyCreateView(request, slug):
    form = RequestToRentPropertyForm()
    if request.method == 'POST':
        form = RequestToRentPropertyForm(request.POST)
        form.instance.propertyObj = get_object_or_404(Property, urlSlug=slug)
        form.instance.studentObj = get_object_or_404(UserStudent, user__user=request.user)
        if form.is_valid():
            form.save()
            notf = Notification.objects.create(
                        fromUser=request.user,
                        toUser=form.instance.propertyObj.landlord.user.user,
                        notificationType='rentRequest',
                        content=form.instance.propertyObj.title,
                        identifier=form.instance.pk,
                    )
            messages.add_message(request, messages.SUCCESS, 'Rent Request Sent Successfully.')
        else:
            for error in form.errors:
                messages.add_message(request, messages.ERROR, form.errors[error])
    return redirect('property:propertyDetail', slug=slug)


@login_required
@user_passes_test(studentAccessTest)
def RequestToTourPropertyCreateView(request, slug):
    form = RequestToTourPropertyForm()
    if request.method == 'POST':
        form = RequestToTourPropertyForm(request.POST)
        form.instance.propertyObj = get_object_or_404(Property, urlSlug=slug)
        form.instance.studentObj = get_object_or_404(UserStudent, user__user=request.user)
        if form.is_valid():
            form.save()
            notf = Notification.objects.create(
                        fromUser=request.user,
                        toUser=form.instance.propertyObj.landlord.user.user,
                        notificationType='tourRequest',
                        content=form.instance.propertyObj.title,
                        identifier=form.instance.pk,
                    )
            messages.add_message(request, messages.SUCCESS, 'Tour Request Sent Successfully.')
        else:
            messages.add_message(request, messages.ERROR, form.errors)
    return redirect('property:propertyDetail', slug=slug)


@login_required
@user_passes_test(studentAccessTest)
def RequestToRentServiceCreateView(request, pk):
    form =RequestToRentServiceForm()
    if request.method == 'POST':
        form = RequestToRentServiceForm(request.POST)
        serviceObj = get_object_or_404(Service, pk=pk)
        studentObj = get_object_or_404(UserStudent, user__user=request.user)
        form.instance.serviceObj = serviceObj
        form.instance.studentObj = studentObj
        if form.is_valid():
            form.save()
            # adminUser = get_user_model().objects.get(is_superuser=True)
            # notf = Notification.objects.create(
            #                 fromUser=request.user,
            #                 toUser=adminUser,
            #                 notificationType='serviceRequest',
            #                 content=serviceObj.serviceName,
            #                 identifier=serviceObj.pk,
            #             )
            messages.add_message(request, messages.SUCCESS, 'Request Sent Successfully.')
        else:
            messages.add_message(request, messages.ERROR, form.errors)
    return redirect('services:servicesDetail', pk=pk)

@login_required
@user_passes_test(landlordAccessTest)
def myrequest(request):
    rentRequest = RequestToRentProperty.objects.filter(propertyObj__landlord__user__user=request.user).order_by('-createdDate')
    tourRequest = RequestToTourProperty.objects.filter(propertyObj__landlord__user__user=request.user).order_by('-createdDate')
    context = {
        'rentRequest': rentRequest,
        'tourRequest': tourRequest
    }
    return render(request, 'checkout/myrequest.html', context=context)


class RequestToRentPropertyDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = RequestToRentProperty
    template_name = "checkout/myrequestrentview.html"

    def test_func(self):
        try:
            return self.request.user.usertype.is_landlord
        except:
            raise Http404


class RequestToTourPropertyDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = RequestToTourProperty
    template_name = "checkout/myrequesttourview.html"

    def test_func(self):
        try:
            return self.request.user.usertype.is_landlord
        except:
            raise Http404

checkout/templates/checkout/myrequest.html
{% include "layout/google-analytics.html" %}
{% include "layout/header.html" %}

{% load static %}
{% comment %} <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>   {% endcomment %}
<style>
	#requestpills > li { padding:5px !important; }  
	#requestpills > li > a { border-radius:50px !important; width:100% !important; padding:5px 20px !important; color:#00297a !important; text-decoration:none; border:2px solid #00297a !important; }  
    #requestpills > li.active > a { background-color: #00297a !important; color:#fff !important; }  
    #requestpills > li > a.active { background-color: #00297a !important; color:#fff !important; }  
    
    .requests_table > thead > tr > th { background-color: #00297a; color:#fff; padding:20px; }
     .addressp { padding-left:40px; }
     .reqtableimg { border-radius:50px; width:30px; height:30px; }
     td > .fa-eye { border-radius:100px; }
</style>
<br>
<br>
<br>
<br>
<br>
<div class="container-fluid">
  <ul class="nav nav-pills nav-justified" id="requestpills">
  <li id="rentbtn" onclick="rentclick()"  style="background-color: transparent !important;"><a class="active" data-toggle="pill" href="#home">Rent Requests</a></li>
  <li id="tourbtn" onclick="tourclick()" style="background-color: transparent !important;"><a data-toggle="pill" href="#menu1">Tour Requests</a></li>
</ul>

<div class="tab-content">
  <div id="home" class="tab-pane fade in active show" style="background-color: transparent !important;">
  <br><br>
	<table class="table table-striped requests_table">
    	<thead>
        	<tr>
                <th style="border-top-left-radius:10px !important;">Property Address</th>
            	<th>Name</th>
                <th>Move In & Move Out</th>
                <th style="border-top-right-radius:10px !important;">Action</th>
            </tr>
        </thead>
        <tbody>
        	{% for rentReq in rentRequest %}
            <tr>
                <td><a href="{% url 'property:propertyDetail' rentReq.propertyObj.urlSlug %}">{{rentReq.propertyObj.title}}</a></td>
            	<td>
                	<img class="reqtableimg" src="{{rentReq.studentObj.profilePicture.url}}" /> &nbsp;
                    <b>{{rentReq.studentObj.user.user.first_name|title}} {{rentReq.studentObj.user.user.last_name}}</b><br>
                	{% comment %} <p class="addressp">{{rentReq.propertyObj.title}}</p> {% endcomment %}
                </td>
                <td>{{rentReq.moveIn}} & {{rentReq.moveOut}}</td>
                <td><a href="{% url 'checkout:rentRequestDetail' rentReq.pk %}"><i class="fa fa-eye btn btn-success btn-sm" style="border-radius: 50px;"> View</i></a></td>
            </tr>
            {% endfor %}
            {% comment %} <tr>
            	<td>
                	<img class="reqtableimg" src="https://i.pinimg.com/736x/5c/24/69/5c24695df36eee73abfbdd8274085ecd--cute-anime-guys-anime-boys.jpg" /> &nbsp;
                    <b>Aravindan Sundaram</b><br>
                	<p class="addressp">23, Test Address Line, Coimbatore, TN</p>
                </td>
                <td><br>14-November-2020 08:30 AM</td>
                <td><br><i class="fa fa-eye btn btn-success btn-sm"> view</i></td>
            </tr>
            <tr>
            	<td>
                	<img class="reqtableimg" src="https://i.pinimg.com/736x/5c/24/69/5c24695df36eee73abfbdd8274085ecd--cute-anime-guys-anime-boys.jpg"/> &nbsp;
                	<b>Arun Prakash</b><br>
                	<p class="addressp">34, Test Address Line, Coimbatore, TN</p>
               	</td>
                <td><br>13-November-2020 10:30 AM</td>
                <td><br><i class="fa fa-eye btn btn-success btn-sm"> View</i></td>
            </tr> {% endcomment %}
        </tbody>
    </table>
  </div>
  <div id="menu1" class="tab-pane fade" style="background-color: transparent !important;">
    <br><br>
	<table class="table table-striped requests_table">
    	<thead>
        	<tr>
                <th style="border-top-left-radius:10px !important;">Property Address</th>
            	<th>Name</th>
                <th>Preference Date | Time</th>
                <th style="border-top-right-radius:10px !important;">Action</th>
            </tr>
        </thead>
        <tbody>
        	{% for tourReq in tourRequest %}
            <tr>
                <td><a href="{% url 'property:propertyDetail' tourReq.propertyObj.urlSlug %}">{{tourReq.propertyObj.title}}</a></td>
            	<td>
                	<img class="reqtableimg" src="{{tourReq.studentObj.profilePicture.url}}" /> &nbsp;
                    <b>{{tourReq.studentObj.user.user.first_name|title}} {{tourReq.studentObj.user.user.last_name}}</b><br>
                	<!-- <p class="addressp">{{tourReq.propertyObj.title}}</p> -->
                </td>
                <td>{{tourReq.preference1Date}} {{tourReq.preference1Time}}</td>
                <td><a href="{% url 'checkout:tourRequestDetail' tourReq.pk %}"><i class="fa fa-eye btn btn-success btn-sm" style="border-radius: 50px;"> View</i></a></td>
            </tr>
            {% endfor %}
            {% comment %} <tr>
            	<td>
                	<img class="reqtableimg" src="https://i.pinimg.com/736x/5c/24/69/5c24695df36eee73abfbdd8274085ecd--cute-anime-guys-anime-boys.jpg" /> &nbsp;
                    <b>Aravindan Sundaram</b><br>
                	<p class="addressp">23, Test Address Line, Coimbatore, TN</p>
                </td>
                <td><br>14-November-2020 08:30 AM</td>
                <td><br><i class="fa fa-eye btn btn-success btn-sm"> view</i></td>
            </tr>
            <tr>
            	<td>
                	<img class="reqtableimg" src="https://i.pinimg.com/736x/5c/24/69/5c24695df36eee73abfbdd8274085ecd--cute-anime-guys-anime-boys.jpg"/> &nbsp;
                	<b>Arun Prakash</b><br>
                	<p class="addressp">34, Test Address Line, Coimbatore, TN</p>
               	</td>
                <td><br>13-November-2020 10:30 AM</td>
                <td><br><i class="fa fa-eye btn btn-success btn-sm"> View</i></td>
            </tr> {% endcomment %}
        </tbody>
    </table>
  </div>
</div>
</div>
<br>
<br>
<!-- <script>
    function rentclick()
    {
        $("#rentbtn > a").css({"background-color":"#002974", "border":"2px solid #002974"});
        $("#tourbtn > a").css({"background-color":"#fff", "border":"2px solid #002974"});
    }

    function tourclick()
    {
        $("#tourbtn.active > a").css({"background-color":"#002974 !important", "border":"2px solid #002974"});
        $("#rentbtn > a").css({"background-color":"#fff", "border":"2px solid #002974"});
    }
</script> -->

{% include "layout/footer.html" %}

checkout/templates/checkout/myrequestrentview.html
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
  <title>SwiftLiving | My Requests</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {% include "layout/google-analytics.html" %}
</head>
<body> {% endcomment %}
{% include "layout/header.html" %}
{% comment %} <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> {% endcomment %}
{% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>  {% endcomment %}
<style>
	#requestpills > li > a { border-radius:50px !important; }  
    #requestpills > li.active > a { background-color: #00297a !important; }  
    
    .requests_table > thead > tr > th { background-color: #00297a; color:#fff; padding:20px; }
     .addressp { padding-left:40px; }
     .reqtableimg { border-radius:50px; width:30px; height:30px; }
     td > .fa-eye { border-radius:100px; }
</style>
<br>
<br>
<br>
<br>
<br>
<div class="container-fluid"><br>
  
  <div class="card">
      <div class="card-header" style="background-color: #98c9ff;"><h3 style="color: #0e0e0e;"><center><b> Request to Rent</b></center></h3></div>
      <div class="card-body">
      	<div class="row">
        	<div class="col-md-2"><h4><b>Address</b></h4></div>
            <div class="col-md-8"><h4>{{object.propertyObj.title}}</h4></div>
            <div class="col-md-2"><a href="{% url 'chat:landlordStudentChat' object.studentObj.user.user.username %}" class="btn btn-primary btn-lg" style="border-radius:50px;">Message</a></div>
        </div>
        <div class="row">
        	<div class="col-md-2"><h4><b>Name</b></h4></div>
            <div class="col-md-8"><h4>{{object.studentObj.user.user.first_name|title}} {{object.studentObj.user.user.last_name}}</h4></div>
        </div>
        <div class="row">
        	<div class="col-md-2"><h4><br><br><b>Request to rent Info</b></h4></div>
            <div class="col-md-8">
            	<h4>
            		<br>
                    <b>Move In & Move Out </b> &nbsp; <i class="fa fa-calendar-o"></i> {{object.moveIn}} & {{object.moveOut}} <br> <br>
                    <b>Occupants </b> &nbsp; <i class="fa fa-users"></i> {{object.occupants}} <br> <br>
            	</h4>
            </div>
        </div>
      </div>
        
      </div>
    </div>

</div>
<br>
<br>
{% include "layout/footer.html" %}
{% comment %} </body>
</html> {% endcomment %}

checkout/templates/checkout/myrequesttourview.html
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
  <title>SwiftLiving | My Requests</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {% include "layout/google-analytics.html" %}
</head>
<body> {% endcomment %}
{% include "layout/header.html" %}
<style>
	#requestpills > li > a { border-radius:50px !important; }  
    #requestpills > li.active > a { background-color: #00297a !important; }  
    
    .requests_table > thead > tr > th { background-color: #00297a; color:#fff; padding:20px; }
     .addressp { padding-left:40px; }
     .reqtableimg { border-radius:50px; width:30px; height:30px; }
     td > .fa-eye { border-radius:100px; }
</style>
<br>
<br>
<br>
<br>
<div class="container-fluid"><br>
  
  <div class="card">
      <div class="card-header" style="background-color: #98c9ff;"><h3 style="color: #0e0e0e;"><center><b> Request to Tour </b></center></h3></div>
      <div class="card-body">
      	<div class="row">
        	<div class="col-md-3"><h4><b>Address</b></h4></div>
            <div class="col-md-7"><h4>{{object.propertyObj.title}}</h4></div>
            <div class="col-md-2"><a href="{% url 'chat:landlordStudentChat' object.studentObj.user.user.username %}" class="btn btn-primary btn-lg" style="border-radius:50px;">Message</a></div>
        </div>
        <div class="row">
        	<div class="col-md-3"><h4><b>Name</b></h4></div>
            <div class="col-md-8"><h4>{{object.studentObj.user.user.first_name|title}} {{object.studentObj.user.user.last_name}}</h4></div>
        </div>
        <div class="row">
        	<div class="col-md-3"><h4><br><b>Request to tour Info</b></h4></div>
            <div class="col-md-8">
            	<h4>
            		<br>
                    <b>Priority Date / Time 1 </b> &nbsp; <i class="fa fa-calendar-o"></i> {{object.preference1Date}} {{object.preference1Time}} <br> <br>
                    {% if object.preference2Date %}
                    <b>Priority Date / Time 2 </b> &nbsp; <i class="fa fa-calendar-o"></i> {{object.preference2Date}} {{object.preference2Time}} <br> <br>
                    {% endif %}
                    {% if object.preference3Date %}
                    <b>Priority Date / Time 3 </b> &nbsp; <i class="fa fa-calendar-o"></i> {{object.preference3Date}} {{object.preference3Time}} <br> <br>
                    {% endif %}
            	</h4>
            </div>
        </div>
      </div>
        
      </div>
    </div>

</div>
<br>
<br>
{% include "layout/footer.html" %}
{% comment %} </body>
</html> {% endcomment %}