chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    path('message_request/<str:requestUser>/<str:fromPage>/', message_request_update, name='message_request_update'),
    # path('message_request_list/', RequestView.as_view(), name='message_request_list'),
    path('create/', create_room, name='create_room'),
    path('create_group/', CreateGroupView.as_view(), name='creategroup'),
    path('groups/', index_group, name='groupindex'),
    path('group/<int:room_name>/', group, name="group"),
    path('room/<int:room_name>/', room, name='room'),
    path('create/<slug:slug>/', landlord_chat, name='landlordchat'),
    path('landlord/student/create/<str:studuser>/', landlord_student_chat, name="landlordStudentChat"),
]

realestatex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/defender/', include('defender.urls')),
    path('', include("users.urls", namespace='userApp')),
    path('',include("property.urls", namespace='propertyApp')),
    path('', include("students.urls", namespace='studentsApp')),
    path('', include("services.urls", namespace='servicesApp')),
    path('', include("checkout.urls", namespace='checkoutApp')),
    path('', include("notifications.urls", namespace='notificationApp')),
    path('', include("discussion.urls", namespace='discussionApp')),
    path('chat/', include("chat.urls", namespace='chatApp')),
    path('', include("resources.urls", namespace='resourcesApp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

app_name = "user"

urlpatterns = [
    path('', CustomLoginView.as_view(), name="home"),
    path('landlord/register/', LandlordSignUpView.as_view(), name="landlordSignup"),
    path('student/register/', StudentSignUpView.as_view(), name="studentSignup"),
    path('logout/', LogoutView.as_view(), name = "logout"),
    path('student/profile/<str:username>/', StudentProfileUpdateView.as_view(), name = "studentProfile"),
    path('student/livingHabits/', StudentLivingHabitsUpdateView, name = "studentLiving"),
    path('landlord/profile/<str:username>/', LandlordProfileUpdateView.as_view(), name = "landlordProfile"),
    path('delete/profile/<str:username>/', UserDeleteView.as_view(), name = "deleteProfile"),
    path('contact/', ContactUSCreateView.as_view(), name = "contactUs"),
    path('forgot-password/', ForgotPasswordView, name="forgotPass"),
    path('forgot-password/auth/change/', ForgotSetPassword, name="setPass"),
    path('verify/', otpverify, name="verifyPhone"),
    path('update/phone/', PhoneNumberUpdate, name="updatePhone"),
    path('resend/code/<int:pk>/', ResendVerificationCode, name="resendCode"),
path('resend/code/call/<int:pk>/', ResendVerificationCodeCall, name="resendCallCode"),
]

users/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login as auth_login, settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse, Http404
from django.contrib.auth.models import User
from twilio.rest import Client

from .models import UserStudent, UserLandLord, UserType, InviteCode, ContactUS, PhoneVerification
from .forms import *
from property.utils import studentAccessTest
import datetime

# Create your views here.

twilioClient = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)

class CustomLoginView(LoginView):
    template_name = 'index.html'

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        user = form.get_user()
        if not user.is_superuser and not user.is_staff:
            phone_verify = self.request.session.get('phone_verify', None)
            update_phone_verify = self.request.session.get('update_phone_verify', None)
            forgot_phone_verify = self.request.session.get('forgot_phone_verify', None)
            if phone_verify:
                del self.request.session['phone_verify']
            if update_phone_verify:
                del self.request.session['update_phone_verify']
            if forgot_phone_verify:
                del self.request.session['forgot_phone_verify']
            if user.usertype.is_student:
                if user.usertype.userstudent.phoneVerified:
                    if PhoneVerification.objects.filter(userObj=user).exists():
                        PhoneVerification.objects.get(userObj=user).delete()
                    auth_login(self.request, form.get_user())
                    return HttpResponseRedirect(self.get_success_url())
                else:
                    if PhoneVerification.objects.filter(userObj=user).exists():
                        phonObj = PhoneVerification.objects.get(userObj=user)
                        if (phonObj.updatedDate < (timezone.now() - timezone.timedelta(minutes=10))):
                            phonObj.delete()
                        else:
                            self.request.session['phone_verify'] = user.username
                            return redirect('user:verifyPhone')
                    self.request.session['phone_verify'] = user.username
                    code = send_verfication_code(to=user.usertype.userstudent.phone)
                    return redirect('user:verifyPhone')
            else:
                if user.usertype.userlandlord.phoneVerified:
                    if PhoneVerification.objects.filter(userObj=user).exists():
                        PhoneVerification.objects.get(userObj=user).delete()
                    auth_login(self.request, form.get_user())
                    return HttpResponseRedirect(self.get_success_url())
                else:
                    if PhoneVerification.objects.filter(userObj=user).exists():
                        phonObj = PhoneVerification.objects.get(userObj=user)
                        if (phonObj.updatedDate < (timezone.now() - timezone.timedelta(minutes=10))):
                            phonObj.delete()
                        else:
                            self.request.session['phone_verify'] = user.username
                            return redirect('user:verifyPhone')
                    self.request.session['phone_verify'] = user.username
                    code = send_verfication_code(to=user.usertype.userlandlord.phone)
                    return redirect('user:verifyPhone')
        else:
            auth_login(self.request, form.get_user())
            return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        try:
            if self.request.user.usertype.is_student:
                return reverse_lazy('property:propertyList')
            else:
                return reverse_lazy('property:propertyManage')
        except:
            return reverse_lazy('user:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["LandlordSignupForm"] = LandlordSignupForm(label_suffix='')
        context["StudentSignupForm"] = StudentSignupForm(label_suffix='')
        context["ForgotPasswordForm"] = ForgotPasswordForm(label_suffix='')
        return context

    def get(self, request):
        if request.user.is_authenticated:
            try:
                if request.user.usertype.is_student:
                    return redirect('property:propertyList')
                else:
                    return redirect('property:propertyManage')
            except:
                pass
        return super().get(self, request)


class LandlordSignUpView(CreateView):
    form_class = LandlordSignupForm
    success_url = "/"
    template_name = 'index.html'

    def form_valid(self, form):
        #creating new user with email (converting into lowercase)
        form.instance.email = form.cleaned_data.get('email').lower()
        valid = super().form_valid(form)
        userObject = UserType.objects.create(user=form.instance,
                        userType="seller")
        # profileImage = form.cleaned_data.get('lanprofilePicture', None)
        # if not profileImage:
        #     profileImage = 'uploads/avatar/profile_avatar.png'
        landlordObject = UserLandLord.objects.create(user=userObject, 
                            phone=form.cleaned_data.get('phone'),
                            # profilePicture=profileImage,
                        )
        # messages.add_message(self.request, messages.SUCCESS, 'Landlord/Sublease Profile created successfully. Sign in to you account.')
        # return redirect('user:home')
        return JsonResponse({'success':'Landlord/Sublease Profile created successfully. Sign in to you account.'}, status=201)

    def form_invalid(self, form):
        invalid = super().form_invalid(form)
        return JsonResponse(form.errors, status=400)

    def get(self, request):
        return redirect('user:home')


def get_or_create_interest(tempInterest):
    tempInterest = tempInterest.capitalize()
    # print(tempInterest)
    return Interest.objects.get_or_create(interest=tempInterest)


class StudentSignUpView(CreateView):
    form_class = StudentSignupForm
    success_url = "/"
    template_name = 'index.html'

    def form_valid(self, form):
        #creating new user with email (converting into lowercase)
        form.instance.email = form.cleaned_data.get('email').lower()
        valid = super().form_valid(form)
        # interests=form.cleaned_data.get('interests')
        interest1 = get_or_create_interest(form.cleaned_data.get('interest1'))
        interest2 = get_or_create_interest(form.cleaned_data.get('interest2'))
        interest3 = get_or_create_interest(form.cleaned_data.get('interest3'))
        

        userObject = UserType.objects.create(user=form.instance,
                        userType="student")
        profileImage = form.cleaned_data.get('profilePicture', None)
        if not profileImage:
            profileImage = 'uploads/avatar/profile_avatar.png'
        studentObject = UserStudent.objects.create(user=userObject, 
                            phone=form.cleaned_data.get('phone'),
                            university=form.cleaned_data.get('university'), 
                            classYear=form.cleaned_data.get('classYear'), 
                            # bio=form.cleaned_data.get('bio'),
                            profilePicture=profileImage,
                            fbLink=form.cleaned_data.get('fblink'),
                            # snapLink=form.cleaned_data.get('snapLink'),
                            instaLink=form.cleaned_data.get('instaLink'),
                            # twitterLink=form.cleaned_data.get('twitterLink'),
                            # sleepScheduleFrom=form.cleaned_data.get('ssFrom'),
                            # sleepScheduleTo=form.cleaned_data.get('ssTo'),
                            # studyHourFrom=form.cleaned_data.get('shFrom'),
                            # studyHourTo=form.cleaned_data.get('shTo'),
                            # tobaccoUsage=form.cleaned_data.get('tbUsage'),
                            # alcoholUsage=form.cleaned_data.get('alUsage'),
                            # cleanliness=form.cleaned_data.get('cleanliness'),
                            # guests=form.cleaned_data.get('guests'),
                        )
        # studentObject.interests.set(interests)
        studentObject.interests.set([interest1[0].pk, interest2[0].pk, interest3[0].pk])
        studentObject.save()

        inviteCode = self.request.GET.get('invite_code', None)
        if inviteCode:
            try:
                newUser = InviteCode.objects.get(inviteCode=inviteCode)
                newUser.studentJoined.add(studentObject)
                newUser.save()
            except InviteCode.DoesNotExist:
                print("Invite codes doesn't match! Ask your friend to resend.")
        
        # messages.add_message(self.request, messages.SUCCESS, 'Student Profile created successfully. Sign in to you account.')
        # return redirect('user:home')
        return JsonResponse({'success':'Student Profile created successfully. Sign in to you account.'}, status=201)

    def form_invalid(self, form):
        invalid = super().form_invalid(form)
        return JsonResponse(form.errors, status=400)

    def get(self, request):
        return redirect('user:home')


class StudentProfileUpdateView(LoginRequiredMixin, UpdateView):

users/templates/users/defenderLockout.html
{% include "layout/header.html" %}
<div class="pxp-content">
    <div class="pxp-agents mt-100">
        <div class="container">
            <center>
             <h3>You have crossed many wrong attempts - Total {{failure_limit|add:1}}</h3> <hr>
             <h5>Try after {{cooloff_time_minutes|floatformat:0}} minutes</h5>
            </center>
        </div>
    </div>
</div>
<br>
<br>
<br>
{% include "layout/footer.html" %}

users/templates/users/profile-delete.html
{% include "layout/header.html" %}


<div class="pxp-content">
    <div class="pxp-agents mt-100">
        <div class="container">
            <div class="row">
                <form action="" method="post">
                    {% csrf_token %}
                    <h5>Hi {{object.first_name}},</h5>
                    <h6>Are you sure you want to delete your 
                        {% if object.usertype.is_landlord %}
                        Seller
                        {% elif object.usertype.is_student %}
                        Student
                        {% endif %}
                        account</h6>
                    {% if object.usertype.is_landlord %}
                        <a href="{% url 'user:landlordProfile' object.username %}">Cancel</a>
                    {% elif object.usertype.is_student %}
                        <a href="{% url 'user:studentProfile' object.username %}">Cancel</a>
                    {% endif %}
                    <input type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% include "layout/footer.html" %}

users/templates/users/profile-landlord.html
{% include "layout/header.html" %}

{% load static %}
<style>
	.pxp-header.fixed-top.pxp-animate { background-color:rgba(4, 113, 166, 1) !important; }
	.form-control { background-color:#f7f7f7; }
	#pictureContainer { display:none; }
</style>

        <div class="pxp-content">
            <div class="pxp-agents" style="margin-top:3%;">
                <div class="container">
					{% if messages %}
						{% for message in messages %}
						{% if message.tags == 'success' %}
							<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
								<strong>{{ message }}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
						{% endif %}
						{% endfor %}
					{% endif %}
                    <div class="row">
                        <div class="col-sm-12 col-md-8 col-lg-8" style="background-color:#fff; border-radius:5px; padding:25px;">
                            <h2 class="pxp-page-header" id="flnameview">
								<b>{{user.first_name|capfirst}} {{user.last_name|capfirst}}</b>
								<span class="pull-right btn btn-default btn-sm" style="background-color:#3a3a3a; color:#fff; cursor:pointer;" onclick="editclick()"><i class="fa fa-edit"></i> Edit</span>
							</h2>
							<br>
							<form action="" method="post" enctype="multipart/form-data">
								{% csrf_token %}
								<small style="color: red;">{{form.landlordProfilecaptcha.errors.as_ul}}</small>
								{% for field in form %}
									{% if field != form.profilePicture and field != form.landlordProfilecaptcha and field != form.phone %}
									<p>
										{{field.label_tag}}
										{{field}}
										<small style="color: red;">{{field.errors.as_ul}}</small>
									</p>
									{% endif %}
								{% endfor %}
								<small style="color: red;">{{form.phone.errors}}</small>
								{{form.landlordProfilecaptcha}}
								{{form.landlordProfilecaptcha.id_for_label|json_script:"recaptchaV3Id"}}
								<script src="{% static 'js/recaptchaReset.js' %}"></script>
								<span>
									<input type="submit" value="Save" class="btn submitbtn" style="background-color:rgba(0, 0, 0, 0.8); color:#fff;">
									<a class="btn btn-danger pull-right" onclick="return confirm('Are you sure to delete your account?');" href="{% url 'user:deleteProfile' user.username %}"><i class="fa fa-trash"></i> Delete my account</a>
								</span>
							<div class="form-group inputitems" id="flnameinput" style="display:none;">
								<label for="pxp-signup-flname">Full Name</label>
								<input type="text" class="form-control" id="pxp-signup-flname" placeholder="Enter your full name" value="Test" style="width:50%; background-color:#f4f4f2;">
							</div>
                            <!--span class="pxp-agent-rating"><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa
							fa-star"></span><span class="fa fa-star"></span></span-->
                            <br>
                        </div>
                        <div class="col-sm-12 offset-lg-1 col-md-4 col-lg-3" style="padding:10px;">
							<center>
                            <!--div class="pxp-agent-photo pxp-cover rounded-lg mt-4 mt-md-5 mt-lg-0" id="profileimg" style="background-image: url(images/agent-4.jpg); background-position: 50% 0%;"></div-->
							{% comment %} {% if object.profilePicture %}
								<img id="output" src="{{object.profilePicture.url}}" style="width:255px; height:300px; border-radius:7px;">
							{% else %}
								<img id="output" src="https://www.w3schools.com/bootstrap/img_avatar1.png" style="width:255px; height:300px; border-radius:7px;">
							{% endif %} {% endcomment %}
							<br><br>
							{% comment %} <span class="pull-right btn btn-default btn-sm" style="background-color:#3a3a3a; color:#fff; cursor:pointer;" onclick="photoclick()"> Upload </span> {% endcomment %}
							<input type="file" accept="image/*" id="photoinput" onchange="loadPhoto(event)" style="display:none;">
							{% comment %} <p id="pictureContainer">{{form.profilePicture}}</p> {% endcomment %}
							{% comment %} <small style="color: red;">{{form.profilePicture.errors}}</small> {% endcomment %}
							</center>
							<br><br><br>
							</form>
							{% if not user.usertype.is_landlord %}
							<h3>Social Media</h3>
							<ul class="list-unstyled pxp-agent-social mt-3 mt-md-4">
								<li><a href="#"><span class="fa fa-facebook"></span></a></li>
								<li><a href="#"><span class="fa fa-twitter"></span></a></li>
								<li><a href="#"><span class="fa fa-pinterest"></span></a></li>
								<li><a href="#"><span class="fa fa-linkedin"></span></a></li>
							</ul>
							<span class="socialicons" id="socialicon1" style="display:none;">
								<i class="fa fa-arrow-down" style="margin-left:10px;"></i>
								<input type="text" class="form-control" id="pxp-signup-college" placeholder="Enter your facebook id"  style="width:100%; background-color:#f4f4f2;">
							</span>
							<span class="socialicons" id="socialicon2" style="display:none;">
								<i class="fa fa-arrow-down" style="margin-left:55px;"></i>
								<input type="text" class="form-control" id="pxp-signup-college" placeholder="Enter your twitter id"  style="width:100%; background-color:#f4f4f2;">
							</span>
							<span class="socialicons" id="socialicon3" style="display:none;">
								<i class="fa fa-arrow-down" style="margin-left:95px;"></i>
								<input type="text" class="form-control" id="pxp-signup-college" placeholder="Enter your pinterest id"  style="width:100%; background-color:#f4f4f2;">
							</span>
							<span class="socialicons" id="socialicon4" style="display:none;">
								<i class="fa fa-arrow-down" style="margin-left:135px;"></i>
								<input type="text" class="form-control" id="pxp-signup-college" placeholder="Enter your linkedin id"  style="width:100%; background-color:#f4f4f2;">
							</span>
							{% endif %}
						</div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12 col-lg-8">
                            <div class="pxp-agent-section mt-4 mt-md-5">
                                
                            </div>
                        </div>
                        <div class="col-sm-12 col-lg-3 offset-lg-1">                            
                            <div class="pxp-agent-section mt-4 mt-md-5">
                                
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

		<script>
			function editclick()
			{
				
				var emailinputstatus = document.getElementById('emailinput').style.display;
			
				if(emailinputstatus == 'none') {										
					document.getElementById('flnameview').style.display = 'none';
					document.getElementById('emailview').style.display = 'none';
					document.getElementById('phoneview').style.display = 'none';
					document.getElementById('addressview').style.display = 'none';
					document.getElementById('collegeview').style.display = 'none';
					
					document.getElementById('flnameinput').style.display = 'inline';
					document.getElementById('emailinput').style.display = 'inline';
					document.getElementById('phoneinput').style.display = 'inline';
					document.getElementById('addressinput').style.display = 'inline';
					document.getElementById('collegeinput').style.display = 'inline';
					
				} else {
				
					document.getElementById('flnameinput').style.display = 'none';
					document.getElementById('emailinput').style.display = 'none';
					document.getElementById('phoneinput').style.display = 'none';
					document.getElementById('addressinput').style.display = 'none';
					document.getElementById('collegeinput').style.display = 'none';
				
					document.getElementById('flnameview').style.display = 'inline';
					document.getElementById('emailview').style.display = 'inline';
					document.getElementById('phoneview').style.display = 'inline';
					document.getElementById('addressview').style.display = 'inline';
					document.getElementById('collegeview').style.display = 'inline';
					
				}
					
			}
			
			function photoclick()
			{
				document.getElementById('{{form.profilePicture.id_for_label}}').click();
			}
			
			function loadPhoto()
			{
				  var output = document.getElementById('output');
					output.src = URL.createObjectURL(event.target.files[0]);
					output.onload = function() {
					  URL.revokeObjectURL(output.src);										  
					  document.getElementById('profileimg').style.backgroundImage = src;
					  
					}
			}
		</script>
		
		
{% include "layout/footer.html" %}

users/templates/users/verificationCode.html
{% include "layout/header.html" %}
<div class="pxp-content">
    <div class="pxp-agents" style="margin-top: 75px;">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6 m-auto">
                    {% if not blocked %}
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #2f7fe9; color: #fff;">
                            {% if forgotpass %}
                            <h3>Forgot Password Verification</h3>
                            {% elif updateVerify%}
                            <h3>Update Phone Verification</h3>
                            {% else %}
                            <h3>Sign up Verification</h3>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <p>We have sent OTP via SMS to the following mobile number</p>
                            {% if forgotpass %}
                            {% load extraTags %}
                            <p>{{verifyUser.phone|phonenumberHide}}</p>
                            {% elif updateVerify%}
                            <p>{{verifyUser.phone}}</p>
                            {% else %}
                            <div class="col-sm-12 m-auto">
                                <form class="form-group" action="{% url 'user:updatePhone' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="input-group mb-3">
                                        {{PhoneNumberForm.verifyPhone}}
                                        <div class="input-group-append">
                                            <button class="btn btn-danger" onclick="visible()" type="button" style="border-top-right-radius: 50px; border-bottom-right-radius: 50px;" id="inputGroupFileAddon04">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="row" id="phone_number_submit_button" style="display: none;">
                                        <div class="col-sm-12 col-md-7">
                                            {{PhoneNumberForm.changePhonecaptcha}}
                                        </div>
                                        <div class="col-sm-12 col-md-4 m-3">
                                            <button class="btn btn-primary"  type="submit">Change</button>
                                        </div>
                                    </div>
                                    {% if messages %}
                                    {% for message in messages %}
                                        {% if message.tags == 'error' %}
                                        <small style="color: red;">{{message}}</small>
                                        {% endif %}
                                    {% endfor %}
                                    {% endif %}
                                </form>
                            </div>
                            {% endif %}
                            <div class="col-sm-12 m-auto">
                                <form class="form-group" action="" method="POST">
                                    {% csrf_token %}
                                    {{VerificationForm.verificationCode}}
                                    <small style="color: red;">{{VerificationForm.verificationCode.errors}}</small>
                                    {% if messages %}
                                    {% for message in messages %}
                                        {% if message.tags == 'warning' %}
                                        <small style="color: red;">{{message}}</small>
                                        {% endif %}
                                    {% endfor %}
                                    {% endif %}
                                    <br>
                                    <input type="submit" class="btn btn-success btn-block" value="Verify{% if verifyUser.wrongAttemptCount <= 3 %} - Only {{verifyUser.wrongAttemptCount}} attempt left{% endif %}"/>
                                </form>
                            </div>
                        </div>
                        {% if verifyUser.resendCodeCount > 0 %}
                        <div class="card-footer">
                            <a href="{% url 'user:resendCallCode' verifyUser.pk %}"> <b>Call instead for verification code?</b></a>
                        </div>
                        {% endif %}
                        {% if verifyUser.resendCodeCount > 0 %}
                        <div class="card-footer">
                            <a href="{% url 'user:resendCode' verifyUser.pk %}">Resend Again? ({{verifyUser.resendCodeCount}} attempt left)</a>
                        </div>
                        {% endif %}
                    <div>
                    {% else %}
                        {% if not forgotpass %}
                        <h5>Sorry, Your account has been blocked, for security concern, because of 10 Wrong attempts. 
                            Try after 10 minutes.
                        </h5>
                        {% else %}
                        <h5>Sorry, Your account has been blocked permanently, for security concern, because of 3 Wrong attempts.</h5>
                        <p>To unblock your account. Follow any one step below:</p>
                        <ol>
                            <li>Mail us: <a href="mailto:helloswiftliving@gmail.com">helloswiftliving@gmail.com</a> from your registered email.</li>
                            <li>If you rembemer your password use that to login.</li>
                        </ol>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% if not forgotpass and not blocked and not updateVerify%}
<script>
    document.getElementById('id_verifyPhone').setAttribute('disabled', true)
    function visible(){
        document.getElementById('id_verifyPhone').removeAttribute('disabled')
        document.getElementById('phone_number_submit_button').style = 'display: flex;'
    }
    function onloadRecaptchaVerify(){
        grecaptcha.render('{{PhoneNumberForm.changePhonecaptcha.id_for_label}}')
    }
</script>
{% endif %}
<br>
<br>
<br>
{% include "layout/footer.html" %}